#!/bin/sh

#################################
# Simple Program Name Shortening
alias g=git

#############################
# Utilities

# Lock the screen (when going AFK)
# Improve with templates
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# recursive dos2unix in current directory
alias dos2lf='dos2unix `find ./ -type f`'

# Flush the DNS on Mac
# Improve with templates
alias dnsflush='dscacheutil -flushcache'

# Empty the Trash on all mounted volumes and the main HDD.
# Also, clear Apple’s System Logs to improve shell startup speed.
# Finally, clear download history from quarantine. https://mths.be/bum
# Improve with templates
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl; sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"

# Files being opened
# Improve with templates
alias files.open='sudo fs_usage -e -f filesystem|grep -v CACHE_HIT|grep -v grep|grep open'
# Files used, anywhere on the filesystem
# Improve with templates
alias files.usage='sudo fs_usage -e -f filesystem|grep -v CACHE_HIT|grep -v grep'
# Files in use in the Users directory
# Improve with templates
alias files.usage.user='sudo fs_usage -e -f filesystem|grep -v CACHE_HIT|grep -v grep|grep Users'

alias game.seek='txt="";for i in {1..20};do txt=$txt"$i. ";done;txt=$txt" Ready or not, here I come";say $txt'

# Git Tools
# assumes git-up is installed (gem install git-up)
# switches to 'develop' branch, updates all local branches (nicely using git-up), removes all local branches already merged into 'develop'
alias gitdev='git checkout develop; git-up; git branch --merged develop | grep -v "\* develop" | xargs -n 1 git branch -d; git branch;'

# IP addresses
# Improve with templates
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias iplocal="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Show active network interfaces
alias ifactive="ifconfig | pcregrep -M -o '^[^\t:]+:([^\n]|\n\t)*status: active'"

# Show network connections
# Often useful to prefix with SUDO to see more system level network usage
alias network.connections='lsof -l -i +L -R -V'
alias network.established='lsof -l -i +L -R -V | grep ESTABLISHED'
alias network.externalip='curl -s http://checkip.dyndns.org/ | sed "s/[a-zA-Z<>/ :]//g"'
alias network.internalip="ifconfig en0 | egrep -o '([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)'"

# Directory listings
# LS_COLORS='no=01;37:fi=01;37:di=07;96:ln=01;36:pi=01;32:so=01;35:do=01;35:bd=01;33:cd=01;33:ex=01;31:mi=00;05;37:or=00;05;37:'
# -G Add colors to ls
# -l Long format
# -h Short size suffixes (B, K, M, G, P)
# -p Postpend slash to folders
alias ls='ls -G -h -p '
alias ll='ls -l -G -h -p '

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# Copy and paste and prune the usless newline
# Improve with templates
alias pbcopynn='tr -d "\n" | pbcopy'

# firewall management
# Improve with templates
alias port-forward-enable="echo 'rdr pass inet proto tcp from any to any port 2376 -> 127.0.0.1 port 2376' | sudo pfctl -ef -"
alias port-forward-disable="sudo pfctl -F all -f /etc/pf.conf"
alias port-forward-list="sudo pfctl -s nat"

# push git repo, but first, use git-up to make sure you are in sync and rebased with the remote
alias pushup="git-up && git push"
# Set the extended MacOS attributes on a file such that Quicklook will open it as text
# Improve with templates
alias qltext='xattr -wx com.apple.FinderInfo "54 45 58 54 21 52 63 68 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00" $1'
#alias qltext2='osascript -e tell application "Finder" to set file type of ((POSIX file "$1") as alias) to "TEXT"'

# Reload the shell (i.e. invoke as a login shell)
# Improve with templates
alias reload="exec $SHELL -l"

# Disable Spotlight
# Improve with templates
alias spotoff="sudo mdutil -a -i off"
# Enable Spotlight
alias spoton="sudo mdutil -a -i on"

# Get macOS Software Updates, and update installed Ruby gems, Homebrew, npm, and their installed packages
# Improve with templates
alias update='sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup; mas upgrade'

alias vtop="vtop --theme wizard"

# Improve with templates
alias jsonfix="pbpaste | jq . | pbcopy"

alias npi="echo '¯\_(ツ)_/¯'"

# Run OpenSSL in a Linux Container
alias linuxssl="docker run --rm -it -v $(pwd):/export frapsoft/openssl $@"

# Most used terraform commands
alias tfi="terraform init"
alias tfp="terraform plan -out /tmp/bootstrap '-input=false'"
alias tfa="terraform apply /tmp/bootstrap"
alias tfd="terraform destroy"
alias tff="terraform fmt"
alias tfo="terraform output"
alias tfv="terraform validate"
alias tfw="terraform workspace"
alias tfc="terraform console"

# Replace vim by neovim
alias vim="nvim"
alias vi="nvim"
alias vimdidd="nvim -d"

# mage
alias mage="go run mage.go"

# Auth finch against ECR
alias ecr-auth="aws ecr get-login-password --region us-east-1 | finch login --username AWS --password-stdin 093535234988.dkr.ecr.us-east-1.amazonaws.com"
